# Generated by Django 4.0.3 on 2022-03-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media')),
                ('Discount_Deal', models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('New Arraivels', 'New Arraivels'), ('New DEALS', 'New DEALS')], max_length=100)),
                ('SALE', models.IntegerField()),
                ('Brand_Name', models.CharField(max_length=500)),
                ('Discount', models.IntegerField()),
                ('Link', models.CharField(max_length=500)),
                ('Rank', models.IntegerField()),
                ('Status', models.CharField(blank=True, choices=[('active', 'active'), ('', 'default')], max_length=300)),
            ],
        ),
    ]
