# Generated by Django 4.0.3 on 2022-03-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/banner_imgs')),
                ('Discount_Deal', models.CharField(max_length=100)),
                ('Quote', models.CharField(max_length=400)),
                ('Discount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='Image',
            field=models.ImageField(upload_to='media/slider_imgs'),
        ),
    ]
