# Generated by Django 4.0.3 on 2022-03-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_banner_alter_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
